"use client";

import { useMemo, useRef, useState } from "react";

export type EditorRatio = "9:16" | "16:9" | "4:5" | "1:1";
interface EditorProps { entered:boolean; ratio:EditorRatio; importedFileName?:string; onClose:()=>void; }
type Tool="move"|"text"|"photo"|"sticker"|"eraser"|"stroke"|"layers";
type TextLayer={id:string;text:string;x:number;y:number;fontFamily:string;fontSize:number;color:string;align:"left"|"center"|"right"};
const TOOLS:Array<{id:Tool;label:string;icon:string}>=[{id:"move",label:"Move",icon:"✦"},{id:"text",label:"Text",icon:"T"},{id:"photo",label:"Photo",icon:"▧"},{id:"sticker",label:"Sticker",icon:"◇"},{id:"eraser",label:"Eraser",icon:"⌁"},{id:"stroke",label:"Stroke",icon:"◌"},{id:"layers",label:"Layers",icon:"≡"}];
const STARTING_FONTS=["Inter","Arial","Georgia","Times New Roman","Courier New"];

export function Editor({entered,ratio,importedFileName,onClose}:EditorProps){
 const [activeTool,setActiveTool]=useState<Tool>("move");
 const [panelOpen,setPanelOpen]=useState(false);
 const [textLayers,setTextLayers]=useState<TextLayer[]>([]);
 const [selectedTextId,setSelectedTextId]=useState<string|null>(null);
 const [fonts,setFonts]=useState(STARTING_FONTS);
 const canvasRef=useRef<HTMLDivElement>(null);
 const dragRef=useRef<{id:string;dx:number;dy:number}|null>(null);
 const canvasStyle=useMemo(()=>({aspectRatio:({"9:16":"9 / 16","16:9":"16 / 9","4:5":"4 / 5","1:1":"1 / 1"} as Record<EditorRatio,string>)[ratio]}),[ratio]);
 const selectedText=textLayers.find(l=>l.id===selectedTextId)??null;
 const addText=()=>{const id=`text-${Date.now()}`;setTextLayers(c=>[...c,{id,text:"Double click to edit",x:50,y:50,fontFamily:fonts[0],fontSize:36,color:"#111111",align:"center"}]);setSelectedTextId(id);setActiveTool("text");setPanelOpen(true);};
 const chooseTool=(tool:Tool)=>{setActiveTool(tool);if(tool==="text"){if(!selectedTextId)addText();else setPanelOpen(true);}else setPanelOpen(tool!=="move");};
 const updateSelectedText=(patch:Partial<TextLayer>)=>{if(!selectedTextId)return;setTextLayers(c=>c.map(l=>l.id===selectedTextId?{...l,...patch}:l));};
 const deleteSelectedText=()=>{if(!selectedTextId)return;setTextLayers(c=>c.filter(l=>l.id!==selectedTextId));setSelectedTextId(null);setPanelOpen(false);};
 const startDrag=(e:React.PointerEvent<HTMLDivElement>,layer:TextLayer)=>{e.stopPropagation();if(activeTool!=="move")return;const canvas=canvasRef.current;if(!canvas)return;const r=canvas.getBoundingClientRect();const px=(e.clientX-r.left)/r.width*100,py=(e.clientY-r.top)/r.height*100;dragRef.current={id:layer.id,dx:px-layer.x,dy:py-layer.y};setSelectedTextId(layer.id);e.currentTarget.setPointerCapture(e.pointerId);};
 const moveText=(e:React.PointerEvent<HTMLDivElement>)=>{const d=dragRef.current,c=canvasRef.current;if(!d||!c)return;const r=c.getBoundingClientRect();const x=Math.max(4,Math.min(96,(e.clientX-r.left)/r.width*100-d.dx)),y=Math.max(5,Math.min(95,(e.clientY-r.top)/r.height*100-d.dy));setTextLayers(cur=>cur.map(l=>l.id===d.id?{...l,x,y}:l));};
 const stopDrag=(e?:React.PointerEvent<HTMLDivElement>)=>{if(e&&e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);dragRef.current=null;};
 const importFont=async(file:File|undefined)=>{if(!file)return;const family=file.name.replace(/\.[^/.]+$/,'')||`Imported Font ${fonts.length+1}`;try{const font=new FontFace(family,`url(${URL.createObjectURL(file)})`);await font.load();document.fonts.add(font);setFonts(c=>c.includes(family)?c:[...c,family]);updateSelectedText({fontFamily:family});}catch{}};
 return <main className={`fixed inset-0 z-50 overflow-hidden bg-[#050505] text-white transition-opacity duration-500 ease-out ${entered?"opacity-100":"opacity-0"}`} aria-label="Paper Stish editor">
  <header className="absolute left-0 right-0 top-0 z-20 flex items-center justify-between px-20 py-20 s:px-30 s:py-25"><button type="button" onClick={onClose} className="group inline-flex items-center gap-10 text-14 tracking-[-0.04em] text-white/75 hover:text-white"><span className="inline-flex size-32 items-center justify-center rounded-full bg-white/8 group-hover:scale-95">×</span><span className="hidden s:inline">MY</span></button><div className="absolute left-1/2 -translate-x-1/2 text-center"><p className="text-16 tracking-[-0.05em]">Paper Stish</p><p className="mt-2 text-11 text-white/40">{importedFileName||ratio}</p></div><button type="button" className="rounded-full bg-white px-18 py-9 text-13 text-black" onClick={()=>window.dispatchEvent(new CustomEvent("paper-stish-export"))}>Export</button></header>
  <div className="absolute inset-0 flex items-center justify-center px-18 pb-100 pt-85"><div className="relative flex h-full w-full items-center justify-center"><div ref={canvasRef} className="relative max-h-full max-w-full overflow-hidden rounded-[18px] bg-[#f2f0ea] shadow-[0_30px_90px_rgba(0,0,0,.42)]" style={{...canvasStyle,width:"min(76vw, 62rem)"}}>
   {textLayers.length===0&&<div className="absolute inset-0 flex items-center justify-center text-center text-black/18 pointer-events-none"><p className="text-16">Your design</p></div>}
   {textLayers.map(layer=>{const selected=layer.id===selectedTextId;return <div key={layer.id} role="button" tabIndex={0} onPointerDown={e=>startDrag(e,layer)} onPointerMove={moveText} onPointerUp={stopDrag} onPointerCancel={stopDrag} onDoubleClick={e=>{e.stopPropagation();setSelectedTextId(layer.id);setActiveTool("text");setPanelOpen(true);}} onClick={()=>{setSelectedTextId(layer.id);setActiveTool("move");setPanelOpen(false);}} className={`absolute max-w-[88%] select-none px-4 py-2 outline-none ${activeTool==="move"?"cursor-move":"cursor-default"} ${selected?"ring-1 ring-black/20 ring-offset-2 ring-offset-[#f2f0ea]":""}`} style={{left:`${layer.x}%`,top:`${layer.y}%`,transform:"translate(-50%,-50%)",fontFamily:layer.fontFamily,fontSize:`${layer.fontSize}px`,color:layer.color,textAlign:layer.align,lineHeight:1.08,whiteSpace:"pre-wrap",touchAction:"none"}}>{layer.text}</div>;})}
   {importedFileName&&<div className="absolute left-12 top-12 rounded-full bg-black/75 px-10 py-6 text-10 text-white/85">{importedFileName}</div>}
  </div></div></div>
  <div className="absolute bottom-0 left-0 right-0 z-20 px-12 pb-18 s:px-30 s:pb-25"><div className="mx-auto flex max-w-[980px] items-end justify-center gap-6 rounded-[22px] border border-white/10 bg-black/55 p-7 backdrop-blur-xl"><div className="flex min-w-0 flex-1 items-center justify-center gap-2 overflow-x-auto">{TOOLS.map(tool=>{const active=activeTool===tool.id;return <button key={tool.id} type="button" onClick={()=>chooseTool(tool.id)} className={`group flex min-w-[54px] shrink-0 flex-col items-center justify-center gap-4 rounded-[15px] px-8 py-8 transition-all ${active?"bg-white text-black":"text-white/65 hover:bg-white/8 hover:text-white"}`}><span className="flex size-21 items-center justify-center text-15">{tool.icon}</span><span className="text-10">{tool.label}</span></button>;})}</div><div className="flex shrink-0 items-center gap-5 border-l border-white/10 pl-7"><button type="button" className="inline-flex size-38 items-center justify-center text-18 text-white/70 hover:text-white">↶</button><button type="button" className="inline-flex size-38 items-center justify-center text-18 text-white/70 hover:text-white">↷</button></div></div></div>
  {panelOpen&&activeTool==="text"&&<div className="absolute bottom-105 left-12 right-12 z-30 mx-auto max-w-[720px]"><div className="rounded-[20px] border border-white/10 bg-[#151515]/95 px-18 py-16 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-14">Text</p><p className="mt-2 text-11 text-white/40">Edit your selected text.</p></div><button type="button" onClick={()=>setPanelOpen(false)} className="size-32 rounded-full bg-white/7">×</button></div><div className="mt-14 grid gap-9"><textarea value={selectedText?.text??""} onChange={e=>updateSelectedText({text:e.target.value})} placeholder="Type something..." rows={2} className="w-full resize-none rounded-[13px] border border-white/10 bg-white/6 px-12 py-10 text-13 text-white outline-none"/><div className="flex flex-wrap gap-7"><button type="button" onClick={addText} className="rounded-full bg-white px-13 py-8 text-11 text-black">+ Add text</button>{selectedText&&<button type="button" onClick={deleteSelectedText} className="rounded-full bg-white/8 px-13 py-8 text-11 text-white/70">Delete</button>}</div><div className="grid gap-9 s:grid-cols-2"><label className="grid gap-5 text-10 text-white/45">Font<select value={selectedText?.fontFamily??fonts[0]} onChange={e=>updateSelectedText({fontFamily:e.target.value})} className="rounded-[11px] border border-white/10 bg-white/6 px-10 py-9 text-12 text-white"><option value="Inter">Inter</option>{fonts.filter(f=>f!=="Inter").map(font=><option key={font} value={font}>{font}</option>)}</select></label><label className="grid gap-5 text-10 text-white/45">Size <span className="text-white/70">{selectedText?.fontSize??36}px</span><input type="range" min="10" max="180" value={selectedText?.fontSize??36} onChange={e=>updateSelectedText({fontSize:Number(e.target.value)})}/></label></div><div className="flex flex-wrap items-center gap-10"><label className="flex items-center gap-7 text-10 text-white/45">Color <input type="color" value={selectedText?.color??"#111111"} onChange={e=>updateSelectedText({color:e.target.value})} className="size-28"/></label>{["left","center","right"].map(align=><button key={align} type="button" onClick={()=>updateSelectedText({align:align as TextLayer["align"]})} className={`rounded-full px-10 py-7 text-10 capitalize ${selectedText?.align===align?"bg-white text-black":"bg-white/7 text-white/60"}`}>{align}</button>)}<label className="cursor-pointer rounded-full bg-white/7 px-12 py-8 text-10 text-white/65">Import font<input type="file" accept=".ttf,.otf,.woff,.woff2" className="hidden" onChange={e=>importFont(e.target.files?.[0])}/></label></div></div></div></div>}
 </main>;
}
